name: 'Build and deploy subgraph'
inputs:
  type:
    description: 'Type of deployment'
    required: true
    default: 'sandbox'
  thegraph_access_token:
    description: 'Thegraph access token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set yarn default shell
      run: yarn config set script-shell /bin/bash
      shell: bash
    - run: TYPE=${{ inputs.type }} yarn prepare-env
      shell: bash
    - run: yarn deploy:eth
      shell: bash
      env:
        THEGRAPH_ACCESS_TOKEN: ${{ inputs.thegraph_access_token }}
    - run: yarn deploy:bsc
      shell: bash
      env:
        THEGRAPH_ACCESS_TOKEN: ${{ inputs.thegraph_access_token }}