name: Deploy subgraph

on:
  push:
    branches:
      - stable
      - sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        network: ['eth', 'bsc', 'arbitrum']
        type: ${{ github.ref == 'refs/heads/stable' && fromJson('["stable-mainnet", "stable-testnet"]') || github.ref == 'refs/heads/sandbox' && fromJson('["sandbox-mainnet", "sandbox-testnet"]') || fromJson('["unknown-type"]') }}

    env:
      NETWORK: ${{ matrix.network }}
      TYPE: ${{ matrix.type }}
      THEGRAPH_ACCESS_TOKEN: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - run: yarn prepare-env

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2

      - name: Build and deploy ${{ matrix.network }} ${{ matrix.type }}
        run: yarn deploy
