name: Deploy subgraph

on:
  push:
    branches:
      - stable
      - sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        network: ['eth', 'bsc'],
        type: ${{ github.ref == 'refs/heads/stable' && ['stable-mainnet', 'stable-testnet'] || github.ref == 'refs/heads/sandbox' && ['sandbox-mainnet', 'sandbox-testnet'] || ['unknown-type'] }},

    env:
      NETWORK: ${{ matrix.network }}
      TYPE: ${{ matrix.type }}
      THEGRAPH_ACCESS_TOKEN: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - run: yarn prepare-env

      - name: Build and deploy ${{ matrix.network }} ${{ matrix.type }}
        run: yarn deploy
